### ISSUE TITLE
Feed de Notícias 

### ISSUE THREAD

**Issue by evertonleite** [evertonleite/ProcessoDeSoftware#2]
Como usuário, irei ver informações em cards, sobre os problemas na cidade que serão solucionados:

- **Título** (Irá destacar o problema selecionado que será solucionado)
- **Horário** (Horário da publicação)
- **Imagem _(Dependendo do problema será inserida ou não)_** (Imagem com relação ao problema, podendo ser ilustrativa ou não)

**Comment by agildojunior** [comment]
Card ✓
Título ✓
Horário ✓
Imagem ✓
